### ISSUE TITLE
什么时候支持windows平台

### ISSUE THREAD

**Issue by jay19453** [CVCUDA/CV-CUDA#110] opened 2023-09-01 08:02 UTC
如题，各位工程师什么时候支持windows平台，很迫切

**Comment by pmikolajczyk** [comment] 2023-09-22 22:56
This is on the roadmap, will update with version.

Can you share your usecase?

**Comment by bhaefnerNV** [comment] 2024-04-26 11:01
Hi @jay19453,
Thank you for your interest in CVCUDA.
This seems to be a duplicate of [92](https://github.com/CVCUDA/CV-CUDA/issues/92). Hence, we will close this ticket and kindly ask you track the mentioned issue.

**Closed by bhaefnerNV** 2024-04-26 11:01 UTC
