### ISSUE TITLE
[QUESTION] 请问是否可以提供windows版本的配置教程（Could you provide a configuration tutorial for the windows version）

### ISSUE THREAD

**Issue by CvBokchoy** [CVCUDA/CV-CUDA#157] opened 2024-05-13 05:45 UTC
因为我是在windows环境下开发，您现在提供的教程貌似不太适合我，请您提供windows配置方案。（Because I am developing in windows environment, the tutorial you provide now seems not suitable for me, please provide windows configuration scheme）

**Comment by dlesage-nvidia** [comment] 2024-05-15 15:33
Hi @CvBokchoy , thank you for your interest in CV-CUDA!
Could you give us more information about your environment? 
Please note that CV-CUDA is currently only compatible with a "Windows Subsystem for Linux" (WSL2) type of environment, with Ubuntu >=20.04 as the underlying distribution.
We do not support native Windows system at this point.

**Comment by CvBokchoy** [comment] 2024-05-16 01:38
> Hi @CvBokchoy , thank you for your interest in CV-CUDA!您好，感谢您对CV—CUDA的关注！ Could you give us more information about your environment? 你能给予我们更多关于你的环境的信息吗？ Please note that CV-CUDA is currently only compatible with a "Windows Subsystem for Linux" (WSL2) type of environment, with Ubuntu >=20.04 as the underlying distribution. 请注意，CV—CUDA目前仅与"Windows Subsystem for Linux"（WSL 2）类型的环境兼容，Ubuntu>= 20.04作为底层发行版。 We do not support native Windows system at this point. 我们不支持本地Windows系统在这一点上。

Thank you for your patient reply. What I mean is that I don't know how to configure under windows, so I hope you can send the relevant readme file.

**Comment by dlesage-nvidia** [comment] 2024-05-16 15:50
Hi @CvBokchoy , there are no Windows-specific instructions, as a WSL2-based configuration is virtually the same as a Ubuntu-based (Linux) one.
Do you have a WSL-based setup?

**Comment by CvBokchoy** [comment] 2024-05-22 02:07
> WSL

I do not plan to use Linux system, because I was developed in Windows, and finally deployed in Windows, I sincerely hope that you can produce a Windows version of the textbook, which will help many developers.

**Comment by dlesage-nvidia** [comment] 2024-05-22 03:09
Hi @CvBokchoy , it is my understanding that you are trying to use CV-CUDA for Windows native development (for instance, using Visual Studio). 

Unfortunately, this use case is not supported currently.
We are considering adding native Windows OS support in a future release.
This feature request seems to be a duplicate of https://github.com/CVCUDA/CV-CUDA/issues/92. Hence, we will close this ticket and kindly ask you track the mentioned issue.

**Closed by dlesage-nvidia** 2024-05-22 03:09 UTC
Labels: feature request
