### ISSUE TITLE
请问现在的版本支持windows吗

### ISSUE THREAD

**Issue by liumingzhu6060** [CVCUDA/CV-CUDA#120] opened 2023-11-15 06:19 UTC
如题

**Comment by ElinLiu0** [comment] 2023-11-15 09:28
不支持，现在只有Linux的x86-64版本和ARM的Jetson平台

**Comment by ElinLiu0** [comment] 2023-11-30 13:31
> @ElinLiu0 hello,
> 
> * 确认一下哈，这个是支持 Nvidia Jetson agx orin developer kit 这个平台么？

应该是可以的，我是在WSL2上跑的，不过现在一直有一个[BUG](https://github.com/CVCUDA/CV-CUDA/issues/119)，他们也没管我

**Comment by bhaefnerNV** [comment] 2024-04-26 11:11
Hi @liumingzhu6060,
Thank you for your interest in CVCUDA.
Currently, we don't have native Windows support, however CV-CUDA is compatible with WSL2 with Ubuntu >= 20.04.
We are considering adding native Windows OS support in a future release.

@WangFengtu1996, with release 0.6.0-beta, we have updated the [list of supported systems](https://github.com/CVCUDA/CV-CUDA#compatibility), ie we currently support Jetson AGX Orin.

Furthermore, this feature on Windows support seems to be a duplicate of [92](https://github.com/CVCUDA/CV-CUDA/issues/92). Hence, we will close this ticket and kindly ask you track the mentioned issue.

**Closed by bhaefnerNV** 2024-04-26 11:11 UTC
Labels: question
